### ISSUE TITLE
Update biojava dependencies

### ISSUE THREAD

**Issue by jendelel** [rdk/p2rank#5]
Hi, 

please update your biojava dependencies to 4.2.8. The url paths to RCSB have changed and parsing PDB files does not work in the older versions any longer (See this  [bug](https://github.com/biojava/biojava/issues/702)). I would send you a pull request, however, I don't have the source code for your forked biojava-strcture-rdk library, which need to be updated as well. 

Thanks, 

Lukas

**Comment by rdk** [comment]
Solved on develop branch, p2rank now depends on standard non-forked biojava 4.2.8.

Forked version was there because older versions of biojava were crashing when parsing some pdb files from standard datasets, but now it seems to be ok. Note: now biojava is probably ignoring the lines form those files that it is not able to parse.

Thanks for the hint.
