### ISSUE TITLE
 exception in phase 'semantic analysis' in source unit

### ISSUE THREAD

**Issue by veronicagamo** [rdk/p2rank#75]
THis error appears ERROR: BUG! exception in phase 'semantic analysis' in source unit '/home/veronica/scipion/software/em/p2rank-2.3/config/default.groovy' Unsupported class file major version 65
00032:   BUG! exception in phase 'semantic analysis' in source unit '/home/veronica/scipion/software/em/p2rank-2.3/config/default.groovy' Unsupported class file major version 65, 
when Protocol failed: Command ' /home/veronica/scipion/software/em/p2rank-2.3/prank predict "-f" "/home/veronica/ScipionUserData/projects/ROS1/Runs/000396_P2RankFindPockets/extra/3zbf.pdb" "-o" "/home/veronica/ScipionUserData/projects/ROS1/Runs/000396_P2RankFindPockets/extra" "-threads" "4"' returned non-zero exit status 1.

**Comment by rdk** [comment]
This looks like Java runtime version mismatch. P2Rank 2.3 you are using supports Java 8 to 15.
The chance is that you have newer version of Java installed and the version of P2Rank is just too old. 
You can check which Java runtime is used by P2Rank by running `echo $JAVA_HOME`.

I'd recommend running the latest version of P2Rank https://github.com/rdk/p2rank/releases/tag/2.4.2 in any case because of many improvements and bug fixes incorporated since then.
